name: deploy-book

# Run this when the master or main branch changes
on:
  push:
    branches:
      - master

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v5

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip # Implicitly uses requirements.txt for cache key

      - name: Install dependencies
        run: pip install -r requirements.txt

      # (optional) Cache your executed notebooks between runs
      # if you have config:
      # execute:
      #   execute_notebooks: cache
      - name: cache executed notebooks
        uses: actions/cache@v4
        with:
          path: _build/.jupyter_cache
          key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build --all .

      # https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _build/html

      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4